### ISSUE TITLE
URL wird nicht geparst

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/WS-Port-Scanner#1]
Bei Übergabe der URL `https://lednerb.eu/` erscheint folgender Fehler:

```
11:36:27 [pool-2-thread-2] WARN : PortScanner - Could not scan Host
port-scanner_1         | java.net.UnknownHostException: lednerb.eu/: Name does not resolve
port-scanner_1         | 	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
port-scanner_1         | 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
port-scanner_1         | 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
port-scanner_1         | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
port-scanner_1         | 	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
port-scanner_1         | 	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
port-scanner_1         | 	at java.net.InetAddress.getByName(InetAddress.java:1077)
port-scanner_1         | 	at de.rub.nds.siwecos.port.scanner.PortScanner.scan(PortScanner.java:44)
port-scanner_1         | 	at de.rub.nds.siwecos.port.PortScannerCallback.run(PortScannerCallback.java:58)
port-scanner_1         | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
port-scanner_1         | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
port-scanner_1         | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
port-scanner_1         | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
port-scanner_1         | 	at java.lang.Thread.run(Thread.java:748)
```

Momentan wird offenbar nur das Schema abgeschnitten.

Bitte fixen.

**Comment by ic0ns** [comment]
Das problem lässt sich von hier nicht reproduzieren und hat eher was mit deinem lokalen Setup zu tun. Wir nutzen den bei dir eingestellten DNS Server um die Domain aufzulösen. Und anscheinend hat das nicht geklappt. Da kann der DomainValidator wenig für.
```
{"name":"Validator","
hasError":false,
"domain":"lednerb.eu",
"originalUrl":"http://lednerb.eu/",
"urlToScan":"https://lednerb.eu",
"urlIsSyntacticalOk":true,
"dnsResolves":true,
"httpCouldConnect":true,
"httpStatusCode":301,
"httpRedirect":true,
"mailServerDomainList":"mxext3.mailbox.org","mxext2.mailbox.org","mxext1.mailbox.org"],
"crawledUrls":["https://lednerb.eu/site.webmanifest"]}```

**Comment by Skeeve** [comment]
> Das problem lässt sich von hier nicht reproduzieren

Doch, wenn Du es nur richtig versuchst ;)

Schau mal bitte den Unterschied im "Domainnamen".

Du:
> "domain":"lednerb.eu",

Staging:
> port-scanner_1         | java.net.UnknownHostException: lednerb.eu/: Name does not resolve

Du schneidest vom domainnamen / der URL zwar "http://" und "https://" ab, vergisst aber eventuelle ":" und "/", gefolgt von irgendwas abzuschneiden. Das Problem ist, dass der Crawler(?) die redirect URL übergibt und die hat eigentlich immer einen "/" angehängt.

Besser wäre es, das übergebene als URL zu parsen und den Host dort rauszufischen. Alternativ sowas wie:

```Java
host= url.replaceAll("^[a-zA-Z0-9.-]+://","").replaceAll("[:/].*$",""); // ungetestet
```

**Comment by ic0ns** [comment]
Ok, dann wäre es an der stelle wichtig den genauen request zu sehen den ihr abschickt.

**Comment by Skeeve** [comment]
@Lednerb hast Du den Request für @ic0ns?

Aber wie schon angedeutet: Es dütfte sowas in der Art wie `https://lednerb.eu/` sein, was Du als url/domain erhältst.

**Comment by Lednerb** [comment]
Moment, hier verwechselt ihr gerade den WS-Port-Scanner (der bekommt eine `url` übermittelt, nicht die Domain) mit dem DomainValidator (der in der Tat die `Domain` bekommt, hier aber nicht relevant ist.)

Der Port-Scanner wird wie alle anderen Scanner über den definierten Scanner-Interface-Request gestartet:
https://github.com/SIWECOS/siwecos-core-api/blob/develop/SCANNER_INTERFACE-DOCS.md#request-interface

**Comment by Lednerb** [comment]
@ic0ns das Problem liegt hier:

https://github.com/SIWECOS/WS-Port-Scanner/blob/a93db6d89bee05e75563925244723c0f2a7c50e7/src/main/java/de/rub/nds/siwecos/port/scanner/PortScanner.java#L35-L40

Hier müsste vernünftig geparst werden, anstatt lediglich das Protokoll abzuschneiden.

**Comment by Skeeve** [comment]
;) Was ich oben schon schrub… Die Alternative wäre

```java
public PortScanner(String host) { 
     host = host.replaceAll("^https?://", ""); // besser ^[a-zA-Z0-9.-]+://"
     host = host.replaceAll("[:/].*$", "");
     this.host = host; 
 } 
```

**Comment by ic0ns** [comment]
Ok, jetzt checke ich was hier das Problem ist. Ich dachte das issue ist im DomainValidator. Mein Fehler. Allerdings sollte der Portscanner nur mit dem output des DomainValidators angesprochen werden. Es macht keinen Sinn den PortScanner mit URLs aufzurufen.

**Comment by ic0ns** [comment]
Ich habe mir das nochmal angeschaut. Das ist imho ein wontfix. Genau für diesen case haben wir den DomainValidator gebaut. Der Port/Mail und TLS Scanner sollte nur mit dem Content des Domain values aus dem DomainValidator aufgerufen werden. Die input sanitisation in alle Scanner zu copy pasten ist meines erachtens nicht sinnvoll.

**Comment by Lednerb** [comment]
@ic0ns 

Das gehört auch nicht in alle Scanner rein, das ist hier die Ausnahme.

Andernfalls müsste für den Port-Scanner eine Ausnahmebehandlung eingebaut werden, was so jetzt nicht trivial machbar ist.

Der Port-Scanner ist Teil von SIWECOS und explizit ein Scanner.
Dadurch ist es verpflichtend, das Scanner-Interface einzuhalten.

Bei diesem haben wir uns explizit darauf geeinigt, dass wir eine URL übergeben.

Der TLS-Scanner hält sich ebenfalls daran, auch wenn die URL nicht benötigt wird.

Bei den MAIL_TLS Scannern ist es ebenfalls der Fall, dass ein `url` Feld übergeben wird, mit der Ausnahmebehandlung, dass der Scanner damit klarkommen muss, dass es sich um eine Domain, und nicht um eine URL handelt. Dies ist aber im gesamten Projekt die Ausnahme gewesen.

Der Port-Scanner hat zuvor ebenfalls die URL übernommen, somit handelt es sich um einen Bug was die Verarbeitung der Eingabe-Parameter anbelangt.

**Comment by ic0ns** [comment]
Das ist nicht das was wir im Dezember besprochen haben als wir die Integration des Crawlers besprochen haben. Damals war klar das Port-Scanner / Mail-Scanner und TLS-Scanner nicht wie normale HTTP Scanner behandelt werden sollen. Deswegen wurde beschlossen einen DomainValidator einzuführen, der die API dabei unterstützen soll festzulegen welcher Scanner mit welchen Input gefüttert werden soll. Um nicht 2 separate Webservices zu pflegen haben wir den Crawler ebenfalls in den DomainValidator eingepflegt und die MX Records auch hier eingebaut. Es macht keinen Sinn den Port/Mail oder TLS Server mit URLS zu füttern. Diese Scanner müssen jeweils nur einmal pro Domain angestoßen werden. Die anderen Scanner müssen mit "urlToScan" + ggf. gecrawlten URLS angestoßen werden.
